services:
  web:
    image: ghcr.io/samurajey/oauth_py:pr-9
    container_name: oauth_py
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ENV_VAR_NAME=value
    env_file:
      - .env
    volumes:
      - ./web:/var/www/html
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    pull_policy: if_not_present
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '128M'
        reservations:
          cpus: '0.05'
          memory: '32M'
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:3
    container_name: couchdb-instance
    ports:
      - "127.0.0.1:5984:5984"
    volumes:
        - ./dbdata:/opt/couchdb/data
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'
        reservations:
          cpus: '0.05'
          memory: '32M'
